### ISSUE TITLE
Suggestions for CI

### ISSUE THREAD

**Issue by henryruhs** [milewski/cross-port-killer#56]
Hey,

I would like to suggest that you test against latest nodejs and drop those who are end of life:
https://nodejs.org/en/about/releases/

A quick win would be to enable the Travis build for Mac:
https://docs.travis-ci.com/user/multi-os/

There us an quite experimental Windows support on Travis but I usually use Appveyor for that:
https://docs.travis-ci.com/user/reference/windows/
https://www.appveyor.com/

Thanks for that scripts and let me know if you need an helpful hand.

**Comment by milewski** [comment]
I have been wanting to try Circle CI, perhaps this is a good opportunity to try them out, I personally use Drone CI and I like it a lot but I don't think they have an open source free tier, 

It has been a while since I update this package there are a few issues on the Readme, like broken badges and spelling mistake, also I have been wondering why kill multiple ports doesn't work often I run `npx cross-port-killer 3000 3001 3002`.. And only 3000 gets killed, I will try work on this when I got some free time, if you are keen to do this switch you are most than welcome :)

**Comment by henryruhs** [comment]
Here comes a first start with PR https://github.com/milewski/cross-port-killer/pull/57

+ Testing node 8, 9, 10, 12 and 13
+ Mac, Linux and Windows

Works perfect with Travis CI... found issue with node 11 and Windows:
https://travis-ci.org/milewski/cross-port-killer/builds/658948381

**Comment by henryruhs** [comment]
According to the `EPIPE` error, I found some code snip that properly is useful to catch it:

```
process.stdin.on('error', error => {
  if (error.code === 'EPIPE') {
    // add code here to handle it
   }
})
```

**Comment by milewski** [comment]
Thanks! I will have a look why it doesn't work on windows

**Comment by henryruhs** [comment]
You are welcome... I close that issue for now - keep on the good work.
